---
- name: Destroy VIP, pool and pool members
  hosts: all
  gather_facts: False
  connection: local

  vars:
    env_prefix:
      fastlane: "FAST-"
      staging: "STG-"
      production: ""
    env_suffix:
      fastlane: "-fast"
      staging: "-test"
      production: ""
    vip_ip: 10.50.6.10

  tasks:
    - name: Destroy a VIP
      bigip_virtual_server:
        partition: test
        state: absent
        provider: "{{ provider }}"
        name: "{{ env_prefix[item.Environment] }}{{ DNSPrefix }}{{ env_suffix[item.Environment] }}.somedomain.com_{{ VIPPort }}_vs"
      loop: "{{ MembersInfo }}"
      delegate_to: localhost
      
    - name: Destroy a pool
      bigip_pool:
        partition: test
        state: absent
        provider: "{{ provider }}"
        name: "{{ env_prefix[item.Environment] }}{{ DNSPrefix }}{{ env_suffix[item.Environment] }}.somedomain.com_{{ VIPPort }}_pool"
      loop: "{{ MembersInfo }}"
      delegate_to: localhost

    - name: Destroy a node
      bigip_node:
        provider: "{{ provider }}"
        partition: test
        state: absent
        name: "{{ item.1.name }}-{{ item.1.host }}"
      loop: "{{ MembersInfo|subelements('MemberNodes') }}"
      delegate_to: localhost

    - name: Destroy an HTTP Monitor
      bigip_monitor_http:
        provider: "{{ provider }}"
        partition: test
        state: absent
        name: "{{ env_prefix[item.Environment] }}{{ DNSPrefix }}{{ env_suffix[item.Environment] }}.somedomain.com_mon"
      loop: "{{ MembersInfo }}"
      delegate_to: localhost
